/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcknowledgementsRouteImport } from './routes/acknowledgements'
import { Route as AiUsageRouteImport } from './routes/ai-usage'
import { Route as BookmarkletDotjsRouteImport } from './routes/bookmarklet[.]js'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OauthClientMetadataDotjsonRouteImport } from './routes/oauth-client-metadata[.]json'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TipJarRouteImport } from './routes/tip-jar'
import { Route as HouseholdIndexRouteImport } from './routes/household.index'
import { Route as HouseholdListRouteImport } from './routes/household.list'
import { Route as HouseholdPlanRouteImport } from './routes/household.plan'
import { Route as HouseholdRecipesRouteImport } from './routes/household.recipes'
import { Route as HouseholdsIndexRouteImport } from './routes/households.index'
import { Route as HouseholdsSwitchRouteImport } from './routes/households.switch'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPlanWeekDoticsRouteImport } from './routes/api/plan/week[.]ics'
import { Route as ApiRecipeImageRecipeIdRouteImport } from './routes/api/recipe-image/$recipeId'
import { Route as ApiRecipeImageStagedRouteImport } from './routes/api/recipe-image/staged'
import { Route as HouseholdRecipesIndexRouteImport } from './routes/household.recipes.index'
import { Route as HouseholdRecipesIdRouteImport } from './routes/household.recipes.$id'
import { Route as HouseholdRecipesNewRouteImport } from './routes/household.recipes.new'
import { Route as HouseholdRecipesImportRouteImport } from './routes/household.recipes_.import'
import { Route as HouseholdRecipesImportBridgeRouteImport } from './routes/household.recipes_.import-bridge'
import { Route as RecipesIdOgDotpngRouteImport } from './routes/recipes.$id_.og[.]png'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcknowledgementsRoute = AcknowledgementsRouteImport.update({
  id: '/acknowledgements',
  path: '/acknowledgements',
  getParentRoute: () => rootRouteImport,
} as any)
const AiUsageRoute = AiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarkletDotjsRoute = BookmarkletDotjsRouteImport.update({
  id: '/bookmarklet.js',
  path: '/bookmarklet.js',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthClientMetadataDotjsonRoute =
  OauthClientMetadataDotjsonRouteImport.update({
    id: '/oauth-client-metadata.json',
    path: '/oauth-client-metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TipJarRoute = TipJarRouteImport.update({
  id: '/tip-jar',
  path: '/tip-jar',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdIndexRoute = HouseholdIndexRouteImport.update({
  id: '/household/',
  path: '/household/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdListRoute = HouseholdListRouteImport.update({
  id: '/household/list',
  path: '/household/list',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdPlanRoute = HouseholdPlanRouteImport.update({
  id: '/household/plan',
  path: '/household/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRecipesRoute = HouseholdRecipesRouteImport.update({
  id: '/household/recipes',
  path: '/household/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIndexRoute = HouseholdsIndexRouteImport.update({
  id: '/households/',
  path: '/households/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsSwitchRoute = HouseholdsSwitchRouteImport.update({
  id: '/households/switch',
  path: '/households/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanWeekDoticsRoute = ApiPlanWeekDoticsRouteImport.update({
  id: '/api/plan/week.ics',
  path: '/api/plan/week.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipeImageRecipeIdRoute = ApiRecipeImageRecipeIdRouteImport.update({
  id: '/api/recipe-image/$recipeId',
  path: '/api/recipe-image/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecipeImageStagedRoute = ApiRecipeImageStagedRouteImport.update({
  id: '/api/recipe-image/staged',
  path: '/api/recipe-image/staged',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRecipesIndexRoute = HouseholdRecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HouseholdRecipesRoute,
} as any)
const HouseholdRecipesIdRoute = HouseholdRecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HouseholdRecipesRoute,
} as any)
const HouseholdRecipesNewRoute = HouseholdRecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HouseholdRecipesRoute,
} as any)
const HouseholdRecipesImportRoute = HouseholdRecipesImportRouteImport.update({
  id: '/household/recipes_/import',
  path: '/household/recipes/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRecipesImportBridgeRoute =
  HouseholdRecipesImportBridgeRouteImport.update({
    id: '/household/recipes_/import-bridge',
    path: '/household/recipes/import-bridge',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecipesIdOgDotpngRoute = RecipesIdOgDotpngRouteImport.update({
  id: '/recipes/$id_/og.png',
  path: '/recipes/$id/og.png',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/ai-usage': typeof AiUsageRoute
  '/bookmarklet.js': typeof BookmarkletDotjsRoute
  '/login': typeof LoginRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tip-jar': typeof TipJarRoute
  '/household/list': typeof HouseholdListRoute
  '/household/plan': typeof HouseholdPlanRoute
  '/household/recipes': typeof HouseholdRecipesRouteWithChildren
  '/households/switch': typeof HouseholdsSwitchRoute
  '/invite/$token': typeof InviteTokenRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/household/': typeof HouseholdIndexRoute
  '/households/': typeof HouseholdsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/plan/week.ics': typeof ApiPlanWeekDoticsRoute
  '/api/recipe-image/$recipeId': typeof ApiRecipeImageRecipeIdRoute
  '/api/recipe-image/staged': typeof ApiRecipeImageStagedRoute
  '/household/recipes/$id': typeof HouseholdRecipesIdRoute
  '/household/recipes/new': typeof HouseholdRecipesNewRoute
  '/household/recipes/import': typeof HouseholdRecipesImportRoute
  '/household/recipes/import-bridge': typeof HouseholdRecipesImportBridgeRoute
  '/recipes/$id/og.png': typeof RecipesIdOgDotpngRoute
  '/household/recipes/': typeof HouseholdRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/ai-usage': typeof AiUsageRoute
  '/bookmarklet.js': typeof BookmarkletDotjsRoute
  '/login': typeof LoginRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tip-jar': typeof TipJarRoute
  '/household/list': typeof HouseholdListRoute
  '/household/plan': typeof HouseholdPlanRoute
  '/households/switch': typeof HouseholdsSwitchRoute
  '/invite/$token': typeof InviteTokenRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/household': typeof HouseholdIndexRoute
  '/households': typeof HouseholdsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/plan/week.ics': typeof ApiPlanWeekDoticsRoute
  '/api/recipe-image/$recipeId': typeof ApiRecipeImageRecipeIdRoute
  '/api/recipe-image/staged': typeof ApiRecipeImageStagedRoute
  '/household/recipes/$id': typeof HouseholdRecipesIdRoute
  '/household/recipes/new': typeof HouseholdRecipesNewRoute
  '/household/recipes/import': typeof HouseholdRecipesImportRoute
  '/household/recipes/import-bridge': typeof HouseholdRecipesImportBridgeRoute
  '/recipes/$id/og.png': typeof RecipesIdOgDotpngRoute
  '/household/recipes': typeof HouseholdRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acknowledgements': typeof AcknowledgementsRoute
  '/ai-usage': typeof AiUsageRoute
  '/bookmarklet.js': typeof BookmarkletDotjsRoute
  '/login': typeof LoginRoute
  '/oauth-client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/tip-jar': typeof TipJarRoute
  '/household/list': typeof HouseholdListRoute
  '/household/plan': typeof HouseholdPlanRoute
  '/household/recipes': typeof HouseholdRecipesRouteWithChildren
  '/households/switch': typeof HouseholdsSwitchRoute
  '/invite/$token': typeof InviteTokenRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/household/': typeof HouseholdIndexRoute
  '/households/': typeof HouseholdsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/plan/week.ics': typeof ApiPlanWeekDoticsRoute
  '/api/recipe-image/$recipeId': typeof ApiRecipeImageRecipeIdRoute
  '/api/recipe-image/staged': typeof ApiRecipeImageStagedRoute
  '/household/recipes/$id': typeof HouseholdRecipesIdRoute
  '/household/recipes/new': typeof HouseholdRecipesNewRoute
  '/household/recipes_/import': typeof HouseholdRecipesImportRoute
  '/household/recipes_/import-bridge': typeof HouseholdRecipesImportBridgeRoute
  '/recipes/$id_/og.png': typeof RecipesIdOgDotpngRoute
  '/household/recipes/': typeof HouseholdRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acknowledgements'
    | '/ai-usage'
    | '/bookmarklet.js'
    | '/login'
    | '/oauth-client-metadata.json'
    | '/offline'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/tip-jar'
    | '/household/list'
    | '/household/plan'
    | '/household/recipes'
    | '/households/switch'
    | '/invite/$token'
    | '/recipes/$id'
    | '/household/'
    | '/households/'
    | '/api/auth/$'
    | '/api/plan/week.ics'
    | '/api/recipe-image/$recipeId'
    | '/api/recipe-image/staged'
    | '/household/recipes/$id'
    | '/household/recipes/new'
    | '/household/recipes/import'
    | '/household/recipes/import-bridge'
    | '/recipes/$id/og.png'
    | '/household/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acknowledgements'
    | '/ai-usage'
    | '/bookmarklet.js'
    | '/login'
    | '/oauth-client-metadata.json'
    | '/offline'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/tip-jar'
    | '/household/list'
    | '/household/plan'
    | '/households/switch'
    | '/invite/$token'
    | '/recipes/$id'
    | '/household'
    | '/households'
    | '/api/auth/$'
    | '/api/plan/week.ics'
    | '/api/recipe-image/$recipeId'
    | '/api/recipe-image/staged'
    | '/household/recipes/$id'
    | '/household/recipes/new'
    | '/household/recipes/import'
    | '/household/recipes/import-bridge'
    | '/recipes/$id/og.png'
    | '/household/recipes'
  id:
    | '__root__'
    | '/'
    | '/acknowledgements'
    | '/ai-usage'
    | '/bookmarklet.js'
    | '/login'
    | '/oauth-client-metadata.json'
    | '/offline'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/tip-jar'
    | '/household/list'
    | '/household/plan'
    | '/household/recipes'
    | '/households/switch'
    | '/invite/$token'
    | '/recipes/$id'
    | '/household/'
    | '/households/'
    | '/api/auth/$'
    | '/api/plan/week.ics'
    | '/api/recipe-image/$recipeId'
    | '/api/recipe-image/staged'
    | '/household/recipes/$id'
    | '/household/recipes/new'
    | '/household/recipes_/import'
    | '/household/recipes_/import-bridge'
    | '/recipes/$id_/og.png'
    | '/household/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcknowledgementsRoute: typeof AcknowledgementsRoute
  AiUsageRoute: typeof AiUsageRoute
  BookmarkletDotjsRoute: typeof BookmarkletDotjsRoute
  LoginRoute: typeof LoginRoute
  OauthClientMetadataDotjsonRoute: typeof OauthClientMetadataDotjsonRoute
  OfflineRoute: typeof OfflineRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TipJarRoute: typeof TipJarRoute
  HouseholdListRoute: typeof HouseholdListRoute
  HouseholdPlanRoute: typeof HouseholdPlanRoute
  HouseholdRecipesRoute: typeof HouseholdRecipesRouteWithChildren
  HouseholdsSwitchRoute: typeof HouseholdsSwitchRoute
  InviteTokenRoute: typeof InviteTokenRoute
  RecipesIdRoute: typeof RecipesIdRoute
  HouseholdIndexRoute: typeof HouseholdIndexRoute
  HouseholdsIndexRoute: typeof HouseholdsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPlanWeekDoticsRoute: typeof ApiPlanWeekDoticsRoute
  ApiRecipeImageRecipeIdRoute: typeof ApiRecipeImageRecipeIdRoute
  ApiRecipeImageStagedRoute: typeof ApiRecipeImageStagedRoute
  HouseholdRecipesImportRoute: typeof HouseholdRecipesImportRoute
  HouseholdRecipesImportBridgeRoute: typeof HouseholdRecipesImportBridgeRoute
  RecipesIdOgDotpngRoute: typeof RecipesIdOgDotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acknowledgements': {
      id: '/acknowledgements'
      path: '/acknowledgements'
      fullPath: '/acknowledgements'
      preLoaderRoute: typeof AcknowledgementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-usage': {
      id: '/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarklet.js': {
      id: '/bookmarklet.js'
      path: '/bookmarklet.js'
      fullPath: '/bookmarklet.js'
      preLoaderRoute: typeof BookmarkletDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-client-metadata.json': {
      id: '/oauth-client-metadata.json'
      path: '/oauth-client-metadata.json'
      fullPath: '/oauth-client-metadata.json'
      preLoaderRoute: typeof OauthClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tip-jar': {
      id: '/tip-jar'
      path: '/tip-jar'
      fullPath: '/tip-jar'
      preLoaderRoute: typeof TipJarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household/': {
      id: '/household/'
      path: '/household'
      fullPath: '/household/'
      preLoaderRoute: typeof HouseholdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household/list': {
      id: '/household/list'
      path: '/household/list'
      fullPath: '/household/list'
      preLoaderRoute: typeof HouseholdListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household/plan': {
      id: '/household/plan'
      path: '/household/plan'
      fullPath: '/household/plan'
      preLoaderRoute: typeof HouseholdPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household/recipes': {
      id: '/household/recipes'
      path: '/household/recipes'
      fullPath: '/household/recipes'
      preLoaderRoute: typeof HouseholdRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/': {
      id: '/households/'
      path: '/households'
      fullPath: '/households/'
      preLoaderRoute: typeof HouseholdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/switch': {
      id: '/households/switch'
      path: '/households/switch'
      fullPath: '/households/switch'
      preLoaderRoute: typeof HouseholdsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan/week.ics': {
      id: '/api/plan/week.ics'
      path: '/api/plan/week.ics'
      fullPath: '/api/plan/week.ics'
      preLoaderRoute: typeof ApiPlanWeekDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipe-image/$recipeId': {
      id: '/api/recipe-image/$recipeId'
      path: '/api/recipe-image/$recipeId'
      fullPath: '/api/recipe-image/$recipeId'
      preLoaderRoute: typeof ApiRecipeImageRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recipe-image/staged': {
      id: '/api/recipe-image/staged'
      path: '/api/recipe-image/staged'
      fullPath: '/api/recipe-image/staged'
      preLoaderRoute: typeof ApiRecipeImageStagedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household/recipes/': {
      id: '/household/recipes/'
      path: '/'
      fullPath: '/household/recipes/'
      preLoaderRoute: typeof HouseholdRecipesIndexRouteImport
      parentRoute: typeof HouseholdRecipesRoute
    }
    '/household/recipes/$id': {
      id: '/household/recipes/$id'
      path: '/$id'
      fullPath: '/household/recipes/$id'
      preLoaderRoute: typeof HouseholdRecipesIdRouteImport
      parentRoute: typeof HouseholdRecipesRoute
    }
    '/household/recipes/new': {
      id: '/household/recipes/new'
      path: '/new'
      fullPath: '/household/recipes/new'
      preLoaderRoute: typeof HouseholdRecipesNewRouteImport
      parentRoute: typeof HouseholdRecipesRoute
    }
    '/household/recipes_/import': {
      id: '/household/recipes_/import'
      path: '/household/recipes/import'
      fullPath: '/household/recipes/import'
      preLoaderRoute: typeof HouseholdRecipesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household/recipes_/import-bridge': {
      id: '/household/recipes_/import-bridge'
      path: '/household/recipes/import-bridge'
      fullPath: '/household/recipes/import-bridge'
      preLoaderRoute: typeof HouseholdRecipesImportBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id_/og.png': {
      id: '/recipes/$id_/og.png'
      path: '/recipes/$id/og.png'
      fullPath: '/recipes/$id/og.png'
      preLoaderRoute: typeof RecipesIdOgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HouseholdRecipesRouteChildren {
  HouseholdRecipesIdRoute: typeof HouseholdRecipesIdRoute
  HouseholdRecipesNewRoute: typeof HouseholdRecipesNewRoute
  HouseholdRecipesIndexRoute: typeof HouseholdRecipesIndexRoute
}

const HouseholdRecipesRouteChildren: HouseholdRecipesRouteChildren = {
  HouseholdRecipesIdRoute: HouseholdRecipesIdRoute,
  HouseholdRecipesNewRoute: HouseholdRecipesNewRoute,
  HouseholdRecipesIndexRoute: HouseholdRecipesIndexRoute,
}

const HouseholdRecipesRouteWithChildren =
  HouseholdRecipesRoute._addFileChildren(HouseholdRecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcknowledgementsRoute: AcknowledgementsRoute,
  AiUsageRoute: AiUsageRoute,
  BookmarkletDotjsRoute: BookmarkletDotjsRoute,
  LoginRoute: LoginRoute,
  OauthClientMetadataDotjsonRoute: OauthClientMetadataDotjsonRoute,
  OfflineRoute: OfflineRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TipJarRoute: TipJarRoute,
  HouseholdListRoute: HouseholdListRoute,
  HouseholdPlanRoute: HouseholdPlanRoute,
  HouseholdRecipesRoute: HouseholdRecipesRouteWithChildren,
  HouseholdsSwitchRoute: HouseholdsSwitchRoute,
  InviteTokenRoute: InviteTokenRoute,
  RecipesIdRoute: RecipesIdRoute,
  HouseholdIndexRoute: HouseholdIndexRoute,
  HouseholdsIndexRoute: HouseholdsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPlanWeekDoticsRoute: ApiPlanWeekDoticsRoute,
  ApiRecipeImageRecipeIdRoute: ApiRecipeImageRecipeIdRoute,
  ApiRecipeImageStagedRoute: ApiRecipeImageStagedRoute,
  HouseholdRecipesImportRoute: HouseholdRecipesImportRoute,
  HouseholdRecipesImportBridgeRoute: HouseholdRecipesImportBridgeRoute,
  RecipesIdOgDotpngRoute: RecipesIdOgDotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
