packages:
  - services/*
  - packages/*

allowBuilds:
  "@swc/core": true
  core-js: false
  esbuild: true
  lightningcss: true

minimumReleaseAgeExclude:
  - "@types/pg@8.20.3"

enableGlobalVirtualStore: true

minimumReleaseAge: 1440 # At least a day
