/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedOperatorsRouteImport } from './routes/_authed.operators'
import { Route as AuthedNetworkChangesRouteImport } from './routes/_authed.network.changes'
import { Route as AuthedNetworkReposRouteImport } from './routes/_authed.network.repos'
import { Route as AuthedNetworkSyncRunsRouteImport } from './routes/_authed.network.sync-runs'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedLocalRecipesIndexRouteImport } from './routes/_authed.local.recipes.index'
import { Route as AuthedLocalRecipesIdRouteImport } from './routes/_authed.local.recipes.$id'
import { Route as AuthedNetworkRecipesIndexRouteImport } from './routes/_authed.network.recipes.index'
import { Route as AuthedNetworkRecipesDidRkeyRouteImport } from './routes/_authed.network.recipes.$did.$rkey'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperatorsRoute = AuthedOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetworkChangesRoute = AuthedNetworkChangesRouteImport.update({
  id: '/network/changes',
  path: '/network/changes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetworkReposRoute = AuthedNetworkReposRouteImport.update({
  id: '/network/repos',
  path: '/network/repos',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetworkSyncRunsRoute = AuthedNetworkSyncRunsRouteImport.update({
  id: '/network/sync-runs',
  path: '/network/sync-runs',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLocalRecipesIndexRoute = AuthedLocalRecipesIndexRouteImport.update({
  id: '/local/recipes/',
  path: '/local/recipes/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLocalRecipesIdRoute = AuthedLocalRecipesIdRouteImport.update({
  id: '/local/recipes/$id',
  path: '/local/recipes/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNetworkRecipesIndexRoute =
  AuthedNetworkRecipesIndexRouteImport.update({
    id: '/network/recipes/',
    path: '/network/recipes/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNetworkRecipesDidRkeyRoute =
  AuthedNetworkRecipesDidRkeyRouteImport.update({
    id: '/network/recipes/$did/$rkey',
    path: '/network/recipes/$did/$rkey',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/operators': typeof AuthedOperatorsRoute
  '/network/changes': typeof AuthedNetworkChangesRoute
  '/network/repos': typeof AuthedNetworkReposRoute
  '/network/sync-runs': typeof AuthedNetworkSyncRunsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/local/recipes/$id': typeof AuthedLocalRecipesIdRoute
  '/local/recipes/': typeof AuthedLocalRecipesIndexRoute
  '/network/recipes/': typeof AuthedNetworkRecipesIndexRoute
  '/network/recipes/$did/$rkey': typeof AuthedNetworkRecipesDidRkeyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/operators': typeof AuthedOperatorsRoute
  '/': typeof AuthedIndexRoute
  '/network/changes': typeof AuthedNetworkChangesRoute
  '/network/repos': typeof AuthedNetworkReposRoute
  '/network/sync-runs': typeof AuthedNetworkSyncRunsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/local/recipes/$id': typeof AuthedLocalRecipesIdRoute
  '/local/recipes': typeof AuthedLocalRecipesIndexRoute
  '/network/recipes': typeof AuthedNetworkRecipesIndexRoute
  '/network/recipes/$did/$rkey': typeof AuthedNetworkRecipesDidRkeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/operators': typeof AuthedOperatorsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/network/changes': typeof AuthedNetworkChangesRoute
  '/_authed/network/repos': typeof AuthedNetworkReposRoute
  '/_authed/network/sync-runs': typeof AuthedNetworkSyncRunsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/local/recipes/$id': typeof AuthedLocalRecipesIdRoute
  '/_authed/local/recipes/': typeof AuthedLocalRecipesIndexRoute
  '/_authed/network/recipes/': typeof AuthedNetworkRecipesIndexRoute
  '/_authed/network/recipes/$did/$rkey': typeof AuthedNetworkRecipesDidRkeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/operators'
    | '/network/changes'
    | '/network/repos'
    | '/network/sync-runs'
    | '/api/auth/$'
    | '/local/recipes/$id'
    | '/local/recipes/'
    | '/network/recipes/'
    | '/network/recipes/$did/$rkey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/operators'
    | '/'
    | '/network/changes'
    | '/network/repos'
    | '/network/sync-runs'
    | '/api/auth/$'
    | '/local/recipes/$id'
    | '/local/recipes'
    | '/network/recipes'
    | '/network/recipes/$did/$rkey'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/operators'
    | '/_authed/'
    | '/_authed/network/changes'
    | '/_authed/network/repos'
    | '/_authed/network/sync-runs'
    | '/api/auth/$'
    | '/_authed/local/recipes/$id'
    | '/_authed/local/recipes/'
    | '/_authed/network/recipes/'
    | '/_authed/network/recipes/$did/$rkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operators': {
      id: '/_authed/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AuthedOperatorsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/network/changes': {
      id: '/_authed/network/changes'
      path: '/network/changes'
      fullPath: '/network/changes'
      preLoaderRoute: typeof AuthedNetworkChangesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/network/repos': {
      id: '/_authed/network/repos'
      path: '/network/repos'
      fullPath: '/network/repos'
      preLoaderRoute: typeof AuthedNetworkReposRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/network/sync-runs': {
      id: '/_authed/network/sync-runs'
      path: '/network/sync-runs'
      fullPath: '/network/sync-runs'
      preLoaderRoute: typeof AuthedNetworkSyncRunsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/local/recipes/': {
      id: '/_authed/local/recipes/'
      path: '/local/recipes'
      fullPath: '/local/recipes/'
      preLoaderRoute: typeof AuthedLocalRecipesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/local/recipes/$id': {
      id: '/_authed/local/recipes/$id'
      path: '/local/recipes/$id'
      fullPath: '/local/recipes/$id'
      preLoaderRoute: typeof AuthedLocalRecipesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/network/recipes/': {
      id: '/_authed/network/recipes/'
      path: '/network/recipes'
      fullPath: '/network/recipes/'
      preLoaderRoute: typeof AuthedNetworkRecipesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/network/recipes/$did/$rkey': {
      id: '/_authed/network/recipes/$did/$rkey'
      path: '/network/recipes/$did/$rkey'
      fullPath: '/network/recipes/$did/$rkey'
      preLoaderRoute: typeof AuthedNetworkRecipesDidRkeyRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedOperatorsRoute: typeof AuthedOperatorsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedNetworkChangesRoute: typeof AuthedNetworkChangesRoute
  AuthedNetworkReposRoute: typeof AuthedNetworkReposRoute
  AuthedNetworkSyncRunsRoute: typeof AuthedNetworkSyncRunsRoute
  AuthedLocalRecipesIdRoute: typeof AuthedLocalRecipesIdRoute
  AuthedLocalRecipesIndexRoute: typeof AuthedLocalRecipesIndexRoute
  AuthedNetworkRecipesIndexRoute: typeof AuthedNetworkRecipesIndexRoute
  AuthedNetworkRecipesDidRkeyRoute: typeof AuthedNetworkRecipesDidRkeyRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOperatorsRoute: AuthedOperatorsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedNetworkChangesRoute: AuthedNetworkChangesRoute,
  AuthedNetworkReposRoute: AuthedNetworkReposRoute,
  AuthedNetworkSyncRunsRoute: AuthedNetworkSyncRunsRoute,
  AuthedLocalRecipesIdRoute: AuthedLocalRecipesIdRoute,
  AuthedLocalRecipesIndexRoute: AuthedLocalRecipesIndexRoute,
  AuthedNetworkRecipesIndexRoute: AuthedNetworkRecipesIndexRoute,
  AuthedNetworkRecipesDidRkeyRoute: AuthedNetworkRecipesDidRkeyRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
