import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Autogenerated from the docs/ folder structure.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
