import { createFileRoute } from "@tanstack/react-router";
import { LegalLink, LegalPage } from "../components/LegalPage";

export const Route = createFileRoute("/ai-usage")({
  component: AiUsagePage,
});

function AiUsagePage() {
  return (
    <LegalPage eyebrow="Transparency" title="AI Usage" ail={1}>
      {/* TODO(dcousineau): write this page by hand. Stub only. */}
      <p>
        Buttery is an experimental project started by <LegalLink href="https://bsky.app/profile/dcousineau.com">@dcousineau.com</LegalLink>. The goal of this project at its outset
        is multi-fold:
      </p>
      <ul>
        <li>To build the recipe management app myself and my partner have wanted.</li>
        <li>
          To play around with <LegalLink href="https://atproto.com/">AT Protocol</LegalLink> and participate in the "Atmosphere".
        </li>
        <li>To play with new-to-me frameworks and tools.</li>
        <li>
          To experiment with different <strong>agentic development</strong> patterns and techniques.
        </li>
      </ul>
      <p>
        As a result you can safely assume most if not all of the code and content in this application was generated by LLM tools (specifically: Claude Code initially). This project
        does not actively integrate with LLMs during its day-to-day execution, and if it ever does this project will be explicitly clear that performing an action will trigger an
        LLM model. I know people have a wide variety of opinions about LLM usage and I would prefer to be upfront and give you the information you need to make an informed choice
        over whether you want to use this application or not.
      </p>
      <p>
        Additionally I have come to appreciate Daniel Meissler's <LegalLink href="https://danielmeissler.com/2023/03/05/ai-influence-levels/">AI Influence Level</LegalLink> rubrik
        for written content and will endeavor to include a notice on any content-heavy page like this one.
      </p>
      <p>
        <strong>This article is deliberatley AIL-1</strong> meaning the words are truly my own and at no point for this page specifically did I ask any LLM to rephrase,
        restructure, or otherwise provide editorial feedback. However it is AIL-1 and not -0 becuase I did have it reformat this page to add links and ensure the visual
        presentation is consistent with the rest of the application.
      </p>
      <p>
        Other pages will likely be AIL-4 where-in I allow my LLM of choice to write the content but I reviewed and refined it (for example: the temporary terms of service page was
        written on a basic idea and then refined as the model left out certain details I felt important to discuss).
      </p>
      <p>
        I appreciate you taking your time if you read this far and hope that this document either alleviated your concerns or helped you quickly decide to not use this service. My
        only request is you respect the intention of this document as a declaration of intent and not an invitation to a negotiation.
      </p>
      <p>
        If you have any questions or concerns you can either file an issue on this project's repository:{" "}
        <LegalLink href="https://github.com/dcousineau/buttery">https://github.com/dcousineau/buttery</LegalLink> or you can reach out to me on Bluesky at{" "}
        <LegalLink href="https://bsky.app/profile/dcousineau.com">@dcousineau.com</LegalLink>
      </p>
    </LegalPage>
  );
}
