import { createFileRoute } from "@tanstack/react-router";
import { AIL_URL, LegalLink, LegalPage } from "../components/LegalPage";
import { seo } from "../lib/seo";
import { WandSparkles } from "lucide-react";

export const Route = createFileRoute("/ai-usage")({
  head: () => ({
    meta: seo({
      title: "AI Usage · Buttery",
      description: "A human-written note on AI usage in Buttery: most code was LLM-generated but the running app does not call LLMs.",
    }),
  }),
  component: AiUsagePage,
});

function AiUsagePage() {
  return (
    <LegalPage eyebrow="Transparency" title="AI Usage" ail={1}>
      {/* TODO(dcousineau): write this page by hand. Stub only. */}
      <p>
        Buttery is an experimental project started by <LegalLink href="https://bsky.app/profile/dcousineau.com">@dcousineau.com</LegalLink>. The goal of this project at its outset
        is multi-fold:
      </p>
      <ul>
        <li>To build the recipe management app myself and my partner have wanted.</li>
        <li>
          To play around with <LegalLink href="https://atproto.com/">AT Protocol</LegalLink> and participate in the "Atmosphere".
        </li>
        <li>To play with new-to-me frameworks and tools.</li>
        <li>
          To experiment with different <strong>agentic development</strong> patterns and techniques.
        </li>
      </ul>
      <h2>LLM Usage Disclosure</h2>
      <p>
        This entire project has been driven and written by LLM agents directed by myself. Specifically, I have abused my Claude Code MAX subscription. As I mentioned above this
        project is an exercise is stretching my comfort zone and trying out new tools for agentic coding.
      </p>
      <p>
        I have come to appreciate Daniel Miessler's <LegalLink href={AIL_URL}>AI Influence Level</LegalLink> rubric for written content and will endeavor to include a notice on any
        content-heavy page like this one.
      </p>
      <p>
        <strong>This article is deliberately AIL-1</strong> meaning the words are truly my own and at no point (for this page specifically) did I ask any LLM to rephrase. However,
        it is AIL-1 and not -0 because I did use Claude Code to reformat this page, to add links, and to ensure the visual presentation is consistent with the rest of the
        application.
      </p>
      <p>
        Other pages will likely be <strong>AIL-4</strong> where-in I allow my LLM of choice to write the content but I reviewed and refined it (for example: the temporary terms of
        service page was written on a basic idea and then refined as the model left out certain details I felt important to discuss).
      </p>
      <h2>LLM Usage In-App</h2>
      <p>
        This application does make use of LLMs for data cleanliness and enrichment purposes. Specifically this app will farm out to a cheap LLM to extract "best guess" information
        about diet, allergies, etc. from new recipes as they come in from users or over the network.
      </p>
      <p>
        Any data generated by Buttery utiziling an LLM will be clearly labeled in app with a{" "}
        <code>
          <WandSparkles size="1em" className="inline-block" />
        </code>{" "}
        icon.
      </p>
      <h2>Final Thoughts</h2>
      <p>
        I appreciate you taking your time if you read this far and hope that this document either alleviated your concerns or helped you quickly decide to not use this service. My
        only request is you respect the intention of this document as a declaration of intent and not an invitation to a negotiation.
      </p>
      <p>
        If you have any questions or concerns you can either file an issue on this project's repository:{" "}
        <LegalLink href="https://github.com/dcousineau/buttery">https://github.com/dcousineau/buttery</LegalLink> or you can reach out to me on Bluesky at{" "}
        <LegalLink href="https://bsky.app/profile/dcousineau.com">@dcousineau.com</LegalLink>
      </p>
    </LegalPage>
  );
}
