/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  issuer: string;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AtprotoCollectionRecipe {
  cid: string;
  collection: Generated<string>;
  deleted_at: Timestamp | null;
  did: string;
  indexed_at: Generated<Timestamp>;
  name: string | null;
  record: Json;
  record_created_at: Timestamp | null;
  record_updated_at: Timestamp | null;
  rev: string;
  rkey: string;
  uri: string;
  validation_status: Generated<string>;
}

export interface AtprotoOauthSession {
  createdAt: Timestamp;
  id: string;
  key: string;
  updatedAt: Timestamp;
  value: string;
}

export interface AtprotoOauthState {
  createdAt: Timestamp;
  id: string;
  key: string;
  value: string;
}

export interface AtprotoRepo {
  did: string;
  first_seen_at: Generated<Timestamp>;
  handle: string | null;
  last_error: string | null;
  last_synced_at: Timestamp | null;
  missing_since: Timestamp | null;
  pds: string | null;
  status: Generated<string>;
}

export interface AtprotoSyncRun {
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  records_deleted: Generated<number>;
  records_upserted: Generated<number>;
  repos_failed: Generated<number>;
  repos_seen: Generated<number>;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface GroceryItem {
  aisle: string;
  checked_at: Timestamp | null;
  checked_by_did: string | null;
  cleared_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_did: string;
  display_name: string;
  food_slug: string | null;
  household_id: string;
  id: string;
  is_manual: Generated<boolean>;
  merge_unit: string | null;
  name_norm: string;
  quantity: Numeric | null;
  quantity_max: Numeric | null;
  unit: string | null;
  unit_dim: string | null;
  updated_at: Generated<Timestamp>;
}

export interface GroceryItemSource {
  added_at: Generated<Timestamp>;
  added_by_did: string;
  id: string;
  item_id: string;
  plan_entry_id: string | null;
  quantity_base: Numeric | null;
  raw_text: string;
  recipe_id: string | null;
  scale: Generated<Numeric>;
}

export interface Household {
  created_at: Generated<Timestamp>;
  created_by_did: string;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  settings: Generated<Json>;
  updated_at: Generated<Timestamp>;
}

export interface HouseholdInvite {
  bound_to_did: string | null;
  created_at: Generated<Timestamp>;
  created_by_did: string;
  expires_at: Timestamp | null;
  household_id: string;
  id: string;
  max_uses: Generated<number>;
  revoked_at: Timestamp | null;
  role: Generated<string>;
  status: Generated<string>;
  token_hash: string;
  uses: Generated<number>;
}

export interface HouseholdMember {
  deleted_at: Timestamp | null;
  did: string;
  household_id: string;
  invited_by_did: string | null;
  joined_at: Generated<Timestamp>;
  role: string;
  tombstoned: Generated<boolean>;
}

export interface HouseholdPreference {
  created_at: Generated<Timestamp>;
  household_id: string;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
  week_start_day: Generated<number>;
}

export interface HouseholdRecipe {
  added_at: Generated<Timestamp>;
  added_by_did: string;
  favorite: Generated<boolean>;
  favorited_at: Timestamp | null;
  household_id: string;
  recipe_id: string;
}

export interface HouseholdRecipeMeta {
  household_id: string;
  key: string;
  ns: string;
  recipe_id: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface HouseholdRecipeNote {
  author_did: string;
  body: string;
  created_at: Generated<Timestamp>;
  household_id: string;
  recipe_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MealPlanEntry {
  body: string | null;
  cooked_at: Timestamp | null;
  cooked_by_did: string | null;
  created_at: Generated<Timestamp>;
  created_by_did: string;
  deleted_at: Timestamp | null;
  household_id: string;
  id: string;
  kind: string;
  plan_date: Timestamp;
  position: number;
  recipe_id: string | null;
  slot: string;
  updated_at: Generated<Timestamp>;
}

export interface Recipe {
  calories: number | null;
  carbohydrate_content: Numeric | null;
  cid: string | null;
  cook_time: string | null;
  cook_time_seconds: number | null;
  cooking_method: string | null;
  description: string | null;
  did: string | null;
  fat_content: Numeric | null;
  id: string;
  indexed_at: Generated<Timestamp>;
  name: string;
  origin: string;
  prep_time: string | null;
  prep_time_seconds: number | null;
  protein_content: Numeric | null;
  published_at: Timestamp | null;
  recipe_category: string | null;
  recipe_cuisine: string | null;
  recipe_yield: string | null;
  record_created_at: Timestamp | null;
  record_updated_at: Timestamp | null;
  rev: string | null;
  rkey: string | null;
  suitable_for_diet: string[] | null;
  total_time: string | null;
  total_time_seconds: number | null;
  uri: string | null;
  visibility: Generated<string>;
}

export interface RecipeAttribution {
  author: string | null;
  display_name: string | null;
  kind: string;
  license: string | null;
  publisher: string | null;
  raw: Json;
  recipe_id: string;
  url: string | null;
}

export interface RecipeCollection {
  cid: string | null;
  created_at: Generated<Timestamp>;
  created_by_did: string;
  description: string | null;
  household_id: string;
  id: string;
  name: string;
  position: number;
  published_at: Timestamp | null;
  published_by_did: string | null;
  record_created_at: Timestamp | null;
  record_stale: Generated<boolean>;
  rev: string | null;
  rkey: string | null;
  updated_at: Generated<Timestamp>;
  uri: string | null;
}

export interface RecipeCollectionEntry {
  added_at: Generated<Timestamp>;
  added_by_did: string;
  collection_id: string;
  household_id: string;
  position: number;
  recipe_id: string;
}

export interface RecipeEnrichment {
  calories_per_serving: number | null;
  carbohydrate_g: Numeric | null;
  /**
   * The classifier run that produced (or, for slugs it found nothing to say about,
   * deliberately omitted) this recipe's recipe_enrichment_label rows.
   *
   * A missing label row is readable as its dimension's default ONLY for slugs this
   * version of the classifier actually evaluates -- never for every slug that has
   * ever existed, or will ever exist, in recipe_vocab. Add a slug to what the
   * classifier evaluates without bumping this column's value, and every
   * already-classified recipe silently reports the default for a slug nothing ever
   * looked at: "never evaluated" becomes indistinguishable from "we checked and
   * found nothing".
   */
  classifier_version: Generated<number>;
  enriched_at: Timestamp | null;
  error: string | null;
  fat_g: Numeric | null;
  fiber_g: Numeric | null;
  input_hash: string | null;
  llm_enriched_at: Timestamp | null;
  llm_error: string | null;
  llm_input_hash: string | null;
  llm_model: string | null;
  llm_prompt_version: number | null;
  /**
   * null | 'ok' | 'error' | 'skipped' (llm plan §3.1).
   *
   * null    -- never attempted. The llm-backfill claim signal, same role null plays
   *            nowhere on the rules side (rules always run synchronously in enrich;
   *            the LLM pass is the one that can be gated off before it starts).
   * 'ok'    -- llm-enrich ran to completion and wrote its labels. llm_version,
   *            llm_input_hash, llm_model, llm_prompt_version and llm_enriched_at
   *            are the record of that run; llm_error is null.
   * 'error' -- llm-enrich ran and failed (schema-invalid model output after
   *            retries, timeout, provider error). llm_error carries the message,
   *            not a stack -- an error nobody can see is a failure nobody can see
   *            (same lesson the sibling 'error' column and atproto_sync_run share).
   * 'skipped' -- the step ran but the gate said no: the env override forced it
   *            off, the PostHog flag was off/unreachable (fail-closed), or a
   *            precondition failed (rules row not status='ok', or its input_hash
   *            is stale for the current content). Recorded, rather than left null,
   *            so a backfill run while the flag is off does not re-claim the same
   *            rows on every pass -- the claim query only re-considers 'skipped'
   *            rows when force or a version bump says to (plan §9.2).
   */
  llm_status: string | null;
  /**
   * The llm-enrich run that produced (or, for slugs it found nothing to say about,
   * deliberately omitted) this recipe's llm:-owned recipe_enrichment_label rows.
   * Defaults to 0, meaning "never run" -- distinct from llm_status IS NULL only in
   * that this column always has a value; llm_status is the field that actually
   * gates whether it means anything yet.
   *
   * TWO VERSION COLUMNS, NOT ONE: a second provider writes into
   * recipe_enrichment_label under its own method prefix (llm:<provider>:<model>@vN,
   * alongside the rules' rules@N), so "which version evaluated this slug" now has
   * two answers, chosen by whichever provider owns the slug:
   *
   *   - Slugs the rules classifier also emits (every allergen, and the diet slugs
   *     in EMITTED_DIET_SLUGS): absence still reads as the default once
   *     recipe_enrichment.classifier_version covered them, exactly as before this
   *     migration. The LLM only ever ADDS to or escalates these rows; it can never
   *     make an absence mean less than the rules already made it mean.
   *   - Slugs only the LLM ever emits (cuisine/*, meal_type/*, spice_level/*, and
   *     the six macro/paleo diet slugs rules have no rule for): absence means
   *     NOTHING -- not "not this one", not "not_detected", nothing -- unless
   *     recipe_enrichment.llm_status = 'ok' AND this column's value covered that
   *     slug at the time it ran. A recipe the flag skipped and a recipe the LLM
   *     genuinely evaluated and found nothing for are the same shape in
   *     recipe_enrichment_label; llm_status and llm_version are the only way to
   *     tell them apart.
   *
   * llm/schema.ts pins the LLM half the same way classify.ts pins the rules half:
   * the emitted slug sets are snapshotted against LLM_ENRICHMENT_VERSION in
   * llm/schema.test.ts, and changing one without the other fails the suite.
   */
  llm_version: Generated<number>;
  nutrition_confidence: Numeric | null;
  nutrition_method: string | null;
  protein_g: Numeric | null;
  recipe_id: string;
  servings: Numeric | null;
  sodium_mg: Numeric | null;
  status: Generated<string>;
  sugar_g: Numeric | null;
}

export interface RecipeEnrichmentLabel {
  confidence: Numeric;
  dimension: string;
  evidence: Json | null;
  method: string;
  recipe_id: string;
  slug: string;
  updated_at: Generated<Timestamp>;
  /**
   * allergen: contains | may_contain | not_detected | unknown -- not_detected is also
   * the default implied when a (recipe, allergen, slug) row is absent.
   * diet: excluded | likely | unknown -- "not excluded" is the default implied when a
   * (recipe, diet, slug) row is absent. Six slugs under this dimension (keto,
   * low_carb, low_fat, low_calorie, diabetic, paleo) are LLM-only -- the rules
   * classifier never emits them; see the table comment.
   * cuisine, meal_type, spice_level: likely -- the only verdict these tag-shaped
   * dimensions ever store. There is no "not this cuisine" verdict; confidence
   * carries strength and absence carries "not this one" (see the table comment for
   * the llm_status / llm_version gate that makes that reading safe).
   *
   * not_detected -- stored or implied by absence -- is NOT a safety claim. It means
   * the responsible classifier found nothing over text it may not have fully
   * parsed. Consumers exclude on contains and may_contain; never render
   * not_detected, or the absence of a row, as "free of".
   */
  verdict: string;
}

export interface RecipeFetchCache {
  body: string;
  byte_size: number | null;
  content_type: string | null;
  fetched_at: Generated<Timestamp>;
  final_url: string | null;
  host: string | null;
  http_status: number | null;
  url: string;
}

export interface RecipeImage {
  alt: string | null;
  aspect_h: number | null;
  aspect_w: number | null;
  blob_cid: string | null;
  blob_mime: string | null;
  blob_size: number | null;
  ordinal: number;
  recipe_id: string;
}

export interface RecipeImportAttempt {
  created_at: Generated<Timestamp>;
  did: string;
  duration_ms: number | null;
  error: string | null;
  extractor: string | null;
  host: string | null;
  household_id: string | null;
  http_status: number | null;
  id: string;
  parsed: Json | null;
  source: Generated<string>;
  status: string;
  url: string;
}

export interface RecipeImportSession {
  did: string;
  failed_count: Generated<number>;
  file_name: string | null;
  finished_at: Timestamp | null;
  household_id: string;
  id: string;
  imported_count: Generated<number>;
  importer: string;
  skipped_count: Generated<number>;
  started_at: Generated<Timestamp>;
  status: string;
  total_count: Generated<number>;
}

export interface RecipeImportSkip {
  client_id: string;
  household_id: string;
  reason: string;
  session_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RecipeIngredient {
  ordinal: number;
  recipe_id: string;
  text: string;
}

export interface RecipeInstruction {
  ordinal: number;
  recipe_id: string;
  text: string;
}

export interface RecipeKeyword {
  keyword: string;
  recipe_id: string;
}

export interface RecipeMeta {
  key: string;
  ns: string;
  recipe_id: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface RecipePendingImage {
  alt: string | null;
  created_at: Generated<Timestamp>;
  mime: string | null;
  object_key: string | null;
  recipe_id: string;
  source_url: string | null;
}

export interface RecipeSearch {
  recipe_id: string;
  search_tsv: string;
}

export interface RecipeVocab {
  dimension: string;
  label: string;
  slug: string;
  source: Generated<string>;
}

export interface RecipeVocabAlias {
  dimension: string;
  external_ref: string;
  slug: string;
}

export interface Session {
  active_household_id: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  did: string | null;
  email: string;
  emailVerified: boolean;
  handle: string | null;
  id: string;
  image: string | null;
  name: string;
  pds: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  atproto_collection_recipe: AtprotoCollectionRecipe;
  atproto_oauth_session: AtprotoOauthSession;
  atproto_oauth_state: AtprotoOauthState;
  atproto_repo: AtprotoRepo;
  atproto_sync_run: AtprotoSyncRun;
  grocery_item: GroceryItem;
  grocery_item_source: GroceryItemSource;
  household: Household;
  household_invite: HouseholdInvite;
  household_member: HouseholdMember;
  household_preference: HouseholdPreference;
  household_recipe: HouseholdRecipe;
  household_recipe_meta: HouseholdRecipeMeta;
  household_recipe_note: HouseholdRecipeNote;
  meal_plan_entry: MealPlanEntry;
  recipe: Recipe;
  recipe_attribution: RecipeAttribution;
  recipe_collection: RecipeCollection;
  recipe_collection_entry: RecipeCollectionEntry;
  recipe_enrichment: RecipeEnrichment;
  recipe_enrichment_label: RecipeEnrichmentLabel;
  recipe_fetch_cache: RecipeFetchCache;
  recipe_image: RecipeImage;
  recipe_import_attempt: RecipeImportAttempt;
  recipe_import_session: RecipeImportSession;
  recipe_import_skip: RecipeImportSkip;
  recipe_ingredient: RecipeIngredient;
  recipe_instruction: RecipeInstruction;
  recipe_keyword: RecipeKeyword;
  recipe_meta: RecipeMeta;
  recipe_pending_image: RecipePendingImage;
  recipe_search: RecipeSearch;
  recipe_vocab: RecipeVocab;
  recipe_vocab_alias: RecipeVocabAlias;
  session: Session;
  user: User;
  verification: Verification;
}
