/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AtprotoCollectionRecipe {
  cid: string;
  collection: Generated<string>;
  deleted_at: Timestamp | null;
  did: string;
  indexed_at: Generated<Timestamp>;
  name: string | null;
  record: Json;
  record_created_at: Timestamp | null;
  record_updated_at: Timestamp | null;
  rev: string;
  rkey: string;
  uri: string;
  validation_status: Generated<string>;
}

export interface AtprotoOauthSession {
  createdAt: Timestamp;
  id: string;
  key: string;
  updatedAt: Timestamp;
  value: string;
}

export interface AtprotoOauthState {
  createdAt: Timestamp;
  id: string;
  key: string;
  value: string;
}

export interface AtprotoRepo {
  did: string;
  first_seen_at: Generated<Timestamp>;
  handle: string | null;
  last_error: string | null;
  last_synced_at: Timestamp | null;
  missing_since: Timestamp | null;
  pds: string | null;
  status: Generated<string>;
}

export interface AtprotoSyncRun {
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  records_deleted: Generated<number>;
  records_upserted: Generated<number>;
  repos_failed: Generated<number>;
  repos_seen: Generated<number>;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface Household {
  created_at: Generated<Timestamp>;
  created_by_did: string;
  deleted_at: Timestamp | null;
  id: string;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface HouseholdInvite {
  bound_to_did: string | null;
  created_at: Generated<Timestamp>;
  created_by_did: string;
  expires_at: Timestamp | null;
  household_id: string;
  id: string;
  max_uses: Generated<number>;
  revoked_at: Timestamp | null;
  role: Generated<string>;
  status: Generated<string>;
  token_hash: string;
  uses: Generated<number>;
}

export interface HouseholdMember {
  deleted_at: Timestamp | null;
  did: string;
  household_id: string;
  invited_by_did: string | null;
  joined_at: Generated<Timestamp>;
  role: string;
  tombstoned: Generated<boolean>;
}

export interface HouseholdRecipe {
  added_at: Generated<Timestamp>;
  added_by_did: string;
  favorite: Generated<boolean>;
  favorited_at: Timestamp | null;
  household_id: string;
  recipe_id: string;
}

export interface HouseholdRecipeNote {
  author_did: string;
  body: string;
  created_at: Generated<Timestamp>;
  household_id: string;
  recipe_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Recipe {
  calories: number | null;
  carbohydrate_content: Numeric | null;
  cid: string | null;
  cook_time: string | null;
  cook_time_seconds: number | null;
  cooking_method: string | null;
  description: string | null;
  did: string | null;
  fat_content: Numeric | null;
  id: string;
  indexed_at: Generated<Timestamp>;
  name: string;
  origin: string;
  prep_time: string | null;
  prep_time_seconds: number | null;
  protein_content: Numeric | null;
  published_at: Timestamp | null;
  recipe_category: string | null;
  recipe_cuisine: string | null;
  recipe_yield: string | null;
  record_created_at: Timestamp | null;
  record_updated_at: Timestamp | null;
  rev: string | null;
  rkey: string | null;
  suitable_for_diet: string[] | null;
  total_time: string | null;
  total_time_seconds: number | null;
  uri: string | null;
  visibility: Generated<string>;
}

export interface RecipeAttribution {
  author: string | null;
  display_name: string | null;
  kind: string;
  license: string | null;
  publisher: string | null;
  raw: Json;
  recipe_id: string;
  url: string | null;
}

export interface RecipeFetchCache {
  body: string;
  byte_size: number | null;
  content_type: string | null;
  fetched_at: Generated<Timestamp>;
  final_url: string | null;
  host: string | null;
  http_status: number | null;
  url: string;
}

export interface RecipeImage {
  alt: string | null;
  aspect_h: number | null;
  aspect_w: number | null;
  blob_cid: string | null;
  blob_mime: string | null;
  blob_size: number | null;
  ordinal: number;
  recipe_id: string;
}

export interface RecipeImportAttempt {
  created_at: Generated<Timestamp>;
  did: string;
  duration_ms: number | null;
  error: string | null;
  extractor: string | null;
  host: string | null;
  household_id: string | null;
  http_status: number | null;
  id: string;
  parsed: Json | null;
  status: string;
  url: string;
}

export interface RecipeIngredient {
  ordinal: number;
  recipe_id: string;
  text: string;
}

export interface RecipeInstruction {
  ordinal: number;
  recipe_id: string;
  text: string;
}

export interface RecipeKeyword {
  keyword: string;
  recipe_id: string;
}

export interface RecipePendingImage {
  alt: string | null;
  created_at: Generated<Timestamp>;
  mime: string | null;
  object_key: string | null;
  recipe_id: string;
  source_url: string | null;
}

export interface RecipeSearch {
  recipe_id: string;
  search_tsv: string;
}

export interface RecipeVocab {
  dimension: string;
  label: string;
  slug: string;
  source: Generated<string>;
}

export interface RecipeVocabAlias {
  dimension: string;
  external_ref: string;
  slug: string;
}

export interface Session {
  active_household_id: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  did: string | null;
  email: string;
  emailVerified: boolean;
  handle: string | null;
  id: string;
  image: string | null;
  name: string;
  pds: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  atproto_collection_recipe: AtprotoCollectionRecipe;
  atproto_oauth_session: AtprotoOauthSession;
  atproto_oauth_state: AtprotoOauthState;
  atproto_repo: AtprotoRepo;
  atproto_sync_run: AtprotoSyncRun;
  household: Household;
  household_invite: HouseholdInvite;
  household_member: HouseholdMember;
  household_recipe: HouseholdRecipe;
  household_recipe_note: HouseholdRecipeNote;
  recipe: Recipe;
  recipe_attribution: RecipeAttribution;
  recipe_fetch_cache: RecipeFetchCache;
  recipe_image: RecipeImage;
  recipe_import_attempt: RecipeImportAttempt;
  recipe_ingredient: RecipeIngredient;
  recipe_instruction: RecipeInstruction;
  recipe_keyword: RecipeKeyword;
  recipe_pending_image: RecipePendingImage;
  recipe_search: RecipeSearch;
  recipe_vocab: RecipeVocab;
  recipe_vocab_alias: RecipeVocabAlias;
  session: Session;
  user: User;
  verification: Verification;
}
