import { defineRailway, github, postgres, project, service } from "railway/iac";

export default defineRailway(() => {
  const db = postgres("postgres");

  // GitHub-triggered deploys: pushes to the repo build & deploy automatically.
  const web = service("buttery", {
    source: github("dcousineau/buttery"),
    build: "pnpm run build",
    start: "pnpm start",
    env: {
      DATABASE_URL: db.env.DATABASE_URL,
      // Public origin — used as better-auth baseURL and to derive the atproto
      // OAuth client_id / redirect URI.
      BETTER_AUTH_URL: "https://buttery-production.up.railway.app",
      // Generated by Railway on first apply in each environment (better-auth
      // wants 32+ chars); preserveExisting keeps the current value thereafter.
      BETTER_AUTH_SECRET: { generator: "secret(44)", preserveExisting: true },
      // Soft-launch gate: serve only the coming-soon page and refuse the login
      // + recipe APIs. Flip to "false" (or remove) at softlaunch. Unset locally
      // so the real app shows in dev.
      COMING_SOON: "true",
    },
  });
  // CDN caching is enabled for this service but is not expressible in the IaC
  // DSL (as of railway@3.6.0 / CLI 5.28); it is managed via `railway cdn`:
  //   railway cdn status --service buttery
  // Current settings: enabled, html-caching=auto, default-ttl=2h, swr honored,
  // purge-on-deploy=html.

  return project("buttery", {
    resources: [db, web],
  });
});
