#!/usr/bin/env bash
#
# Vendor the brand webfonts (docs/BRAND.md: Alfa Slab One for display, Rubik for
# everything else) out of Google Fonts and into the repo, so neither the app nor
# the docs site fetches type from a third party at runtime.
#
# Why vendored: an `@import url("https://fonts.googleapis.com/…")` is a hard
# runtime dependency on a CDN that is blocked in some networks (Claude Code cloud
# sessions among them — see docs/CLAUDE.md), and it leaks a request per visitor
# to a third party. The server-side OG renderer already vendors the same two
# families as TTF for the same reason (services/web/src/server/og/fonts/).
#
# What it writes, for each of the two consumers:
#   services/web/public/fonts/*.woff2     + services/web/src/fonts.css
#   services/docs/static/fonts/*.woff2    + services/docs/src/css/fonts.css
# Both directories are served at /fonts/… (Docusaurus `baseUrl` is "/"), so the
# generated CSS uses absolute URLs and is byte-identical between the two.
#
# The generated CSS is a faithful copy of what Google serves: one @font-face per
# family × weight × subset, keeping the `unicode-range` descriptors, so browsers
# still download only the subsets a page actually uses. Both files are generated
# — edit this script, not them.
#
# Usage: scripts/update-fonts.sh     (re-run to pick up upstream font updates)

set -euo pipefail

# Same query the CSS files used before vendoring. Add a weight here and re-run.
FAMILY_QUERY="family=Alfa+Slab+One&family=Rubik:wght@400;500;600;700&display=swap"

# A modern browser UA is load-bearing: the css2 endpoint serves woff2 (plus the
# unicode-range subsetting) only to user agents it believes support it, and
# falls back to a single fat TTF otherwise.
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

echo "Fetching the Google Fonts stylesheet…"
curl -fsS -A "$UA" "https://fonts.googleapis.com/css2?${FAMILY_QUERY}" -o "$work_dir/upstream.css"

# Split the upstream stylesheet into (a) a download manifest of "url filename"
# pairs and (b) the same CSS with each remote src rewritten to /fonts/<filename>.
# Each @font-face block is preceded by a `/* subset */` comment, which is the
# only place the subset name appears — hence the running `subset` variable.
awk -v manifest="$work_dir/manifest.txt" '
  /^\/\* .* \*\/$/ { subset = $2; next }
  /font-family:/ {
    family = $0
    sub(/.*font-family: *./, "", family)
    sub(/.;.*/, "", family)
    slug = tolower(family)
    gsub(/ /, "-", slug)
  }
  /font-style:/ { style = $2; sub(/;/, "", style) }
  /font-weight:/ { weight = $2; sub(/;/, "", weight) }
  /src: *url\(/ {
    url = $0
    sub(/.*url\(/, "", url)
    sub(/\).*/, "", url)
    file = slug "-" weight (style == "italic" ? "-italic" : "") "-" subset ".woff2"
    print url, file > manifest
    print "  src: url(/fonts/" file ") format(\x27woff2\x27);"
    next
  }
  { print }
' "$work_dir/upstream.css" > "$work_dir/fonts.css"

count="$(wc -l < "$work_dir/manifest.txt" | tr -d ' ')"
echo "Downloading $count font files…"
mkdir -p "$work_dir/files"
while read -r url file; do
  curl -fsS "$url" -o "$work_dir/files/$file"
done < "$work_dir/manifest.txt"

header="/*
 * GENERATED by scripts/update-fonts.sh — do not edit.
 *
 * Self-hosted copies of the brand faces (docs/BRAND.md). Re-run the script to
 * refresh them; the .woff2 files live alongside, served at /fonts/.
 */
"

# The OFL permits redistribution as long as the license travels with the fonts,
# so every generated directory gets this note (same deal as the vendored OG
# TrueType in services/web/src/server/og/fonts/LICENSE.md).
license="# Vendored brand webfonts

GENERATED by \`scripts/update-fonts.sh\` — do not hand-edit this directory.

The \`.woff2\` files are the two brand families from \`docs/BRAND.md\` (Alfa Slab
One for display, Rubik for everything else), taken from
[Google Fonts](https://fonts.google.com) and licensed under the
[SIL Open Font License 1.1](https://openfontlicense.org/), which permits shipping
them with this app as long as the license travels with them — that is what this
file is for.

They are self-hosted rather than loaded from the Google Fonts CDN so the app has
no third-party runtime dependency for its type: the CDN is a request per visitor
to someone else's server, and it is blocked outright on some networks. One file
per family × weight × subset, with the upstream \`unicode-range\` descriptors kept
in the generated CSS, so a browser still downloads only the subsets a page uses.
"

for target in "services/web/public/fonts:services/web/src/fonts.css" \
              "services/docs/static/fonts:services/docs/src/css/fonts.css"; do
  files_dir="$repo_root/${target%%:*}"
  css_file="$repo_root/${target##*:}"

  rm -rf "$files_dir"
  mkdir -p "$files_dir"
  cp "$work_dir/files"/*.woff2 "$files_dir/"
  printf '%s' "$license" > "$files_dir/LICENSE.md"

  printf '%s\n' "$header" > "$css_file"
  cat "$work_dir/fonts.css" >> "$css_file"

  echo "  wrote ${target%%:*}/ ($count files) and ${target##*:}"
done

# Upstream's formatting isn't oxfmt's, and the generated CSS is committed — run
# the formatter here so a refresh doesn't leave `pnpm format:check` red.
if command -v pnpm >/dev/null; then
  pnpm exec oxfmt "$repo_root/services/web/src/fonts.css" \
    "$repo_root/services/docs/src/css/fonts.css" >/dev/null
fi

echo
echo "Done. Restart the web dev server if it is running — Vite indexes public/"
echo "at startup, so it serves 404s for the recreated files until it does."
