import { xrpc } from "@atproto/lex";
import * as recipeLex from "../../lexicons/exchange/recipe/recipe.js";
import getRecord, { $params as getRecordParams } from "../../lexicons/com/atproto/repo/getRecord.js";
import resolveHandleQuery, { $params as resolveHandleParams } from "../../lexicons/com/atproto/identity/resolveHandle.js";

const APPVIEW = "https://public.api.bsky.app";

export const RECIPE_COLLECTION = "exchange.recipe.recipe";

/**
 * exchange.recipe.recipe record type, generated by @atproto/lex from the
 * published lexicon (`lexicons/exchange.recipe.recipe.json`). Regenerate with
 * `pnpm lex:build`. The vendored lexicons were patched to satisfy lex-schema
 * 0.2.2 — see `lexicons/PATCHES.md` for the diffs from the on-network lexicon.
 */
export type RecipeRecord = recipeLex.Main;

export interface RecipeResult {
  uri: string;
  cid?: string;
  did: string;
  rkey: string;
  value: RecipeRecord;
}

interface ParsedAtUri {
  authority: string;
  collection: string;
  rkey: string;
}

/**
 * Accepts:
 *   at://did:plc:xxx/exchange.recipe.recipe/rkey
 *   at://handle.example.com/exchange.recipe.recipe/rkey
 *   handle.example.com/rkey  (collection implied)
 */
export function parseRecipeRef(input: string): ParsedAtUri {
  const trimmed = input.trim().replace(/^at:\/\//, "");
  const parts = trimmed.split("/").filter(Boolean);
  if (parts.length === 3) {
    const [authority, collection, rkey] = parts;
    return { authority, collection, rkey };
  }
  if (parts.length === 2) {
    const [authority, rkey] = parts;
    return { authority, collection: RECIPE_COLLECTION, rkey };
  }
  throw new Error("Expected an AT-URI like at://handle/exchange.recipe.recipe/rkey");
}

// Return type is intentionally inferred (a lex-branded DID string), not
// annotated, so a shape change in the lex client surfaces as a compile error
// here rather than being silently widened.
export async function resolveHandle(handle: string) {
  // `.parse` validates the raw handle and returns lex's branded param type —
  // the honest boundary conversion, no `as`. Throws if the handle is malformed.
  const { payload } = await xrpc(APPVIEW, resolveHandleQuery, { params: resolveHandleParams.parse({ handle }) });
  return payload.body.did;
}

/** Resolve a DID document and extract the PDS service endpoint. */
export async function resolvePds(did: string): Promise<string> {
  let docUrl: string;
  if (did.startsWith("did:plc:")) {
    docUrl = `https://plc.directory/${did}`;
  } else if (did.startsWith("did:web:")) {
    const host = did.slice("did:web:".length).split(":").join("/");
    docUrl = `https://${decodeURIComponent(host)}/.well-known/did.json`;
  } else {
    throw new Error(`Unsupported DID method: ${did}`);
  }
  const res = await fetch(docUrl);
  if (!res.ok) throw new Error(`Failed to resolve DID document for ${did}`);
  const doc = (await res.json()) as {
    service?: Array<{ id: string; type: string; serviceEndpoint: string }>;
  };
  const pds = doc.service?.find((s) => s.id.endsWith("#atproto_pds") || s.type === "AtprotoPersonalDataServer");
  if (!pds) throw new Error(`No PDS endpoint in DID document for ${did}`);
  return pds.serviceEndpoint;
}

/**
 * Fetch a recipe record by reference. Public records — no auth required.
 * Resolution chain: handle → DID → DID doc → PDS → com.atproto.repo.getRecord.
 */
export async function fetchRecipe(ref: string): Promise<RecipeResult> {
  const { authority, collection, rkey } = parseRecipeRef(ref);
  const did = authority.startsWith("did:") ? authority : await resolveHandle(authority);
  const pds = await resolvePds(did);
  const { payload } = await xrpc(pds, getRecord, { params: getRecordParams.parse({ repo: did, collection, rkey }) });
  const body = payload.body;

  // xrpc() already lifts the response into lex's data model (blobs → BlobRef,
  // etc.), so the nested record validates directly. getRecord types `value` as
  // `unknown`, so validate it against the recipe schema ourselves.
  const parsed = recipeLex.$safeParse(body.value);
  if (!parsed.success) {
    throw new Error(`Record at ${body.uri} failed exchange.recipe.recipe validation: ${parsed.issues.map((i) => `${i.path.join(".")}: ${i.code}`).join("; ")}`);
  }
  return { uri: body.uri, cid: body.cid, did, rkey, value: parsed.value };
}
